version: "3.6"



services:
  caddy:
    image: caddy:2.0.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/volumes/caddy/:/data
      - .Caddyfile:/etc/caddy/Caddyfile
    network_mode: host
